image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Run automated API tests using Postman CLI
        script:
          # Install Postman CLI
          - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          # Login using your API Key
          - postman login --with-api-key PMAK-63d7db49a2ae21287acdf62c-29331a01a47939557e3d509ab4c15efa0e
          # Run your collection using Postman CLI
          - postman collection run "25527043-b863b9fb-2300-4c63-986d-96da96bb2473"